#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Yocto QEMU EDU learning project contributors
# SPDX-License-Identifier: MIT
"""Create or verify the repository source checksum manifest."""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path


MANIFEST = "SHA256SUMS"


def source_files(root: Path) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "--cached"],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    return sorted(
        path.replace("\\", "/")
        for path in result.stdout.splitlines()
        if path and path != MANIFEST
    )


def staged_bytes(root: Path, relative: str) -> bytes:
    result = subprocess.run(
        ["git", "show", f":{relative}"],
        cwd=root,
        check=True,
        capture_output=True,
    )
    return result.stdout


def render(root: Path) -> str:
    # REUSE-IgnoreStart
    lines = [
        "# SPDX-FileCopyrightText: 2026 Yocto QEMU EDU learning project contributors",
        "# SPDX-License-Identifier: MIT",
        "# Generated by scripts/update_checksums.py; SHA256SUMS is excluded from itself.",
    ]
    # REUSE-IgnoreEnd
    for relative in source_files(root):
        digest = hashlib.sha256(staged_bytes(root, relative)).hexdigest()
        lines.append(f"{digest}  ./{relative}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    parser.add_argument("--repo", default=".", help="repository root")
    args = parser.parse_args()
    root = Path(args.repo).resolve()
    expected = render(root)
    path = root / MANIFEST
    if args.check:
        actual = path.read_text(encoding="utf-8") if path.is_file() else ""
        if actual != expected:
            print("checksums: FAIL: run python3 scripts/update_checksums.py", file=sys.stderr)
            return 1
        print("checksums: PASS")
        return 0
    path.write_text(expected, encoding="utf-8", newline="\n")
    print(f"updated {MANIFEST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
